name: Code Quality Check

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.13

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox

            - name: Run Linting
              run: tox -e lint

    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.13

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox

            - name: Run Formatting
              run: tox -e format

    type_check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.13

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox

            - name: Run Type Check
              run: tox -e type_check

    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.13

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox

            - name: Run Tests
              run: tox -e test
