name: Python Package CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev, test, build]"

    - name: Run Tests
      run: pytest ./tests/

    - name: Build and Publish
      if: success() && github.ref == 'refs/heads/main'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        python -m twine upload --skip-existing --non-interactive --verbose dist/*