name: Publish Package

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
env:
  env_var: ${{ vars.PROD_PYPI_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Test Environment Variables
        run: |
          env
          echo ${{ vars.PROD_PYPI_TOKEN }}

      - name: Publish Package
        run: tox -e publish
