name: Publish Package

on:
    workflow_dispatch:
    pull_request:
        types: [closed]
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.13

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox

            - name: Run Linting and Formatting
              run: tox -e publish
              env:
                  PROD_PYPI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
